config/routes.rb
Rails.application.routes.draw do
 
 
  

  resources :attendace3s
 # resources :attendance2s 
  resources :employee2s
  get 'home/index'
  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'
   resources :users
   root 'home#index'
resources :sessions, only: [:new, :create, :destroy]
get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'welcome',to: 'sessions#welcome', as: 'welcome'
get 'new', to: 'employee2s#new', as:  'new'

resources :employee3s, only: [:show, :index, :new, :create, :edit, :update, :destroy]



 get  'home/about'

get  'employee2s/list'

 #root 'employee2s#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendace3.rb
class Attendace3 < ApplicationRecord
	
end

app/models/attendance2.rb
class Attendance2 < ApplicationRecord
	belongs_to :employee2
end

app/models/employee2.rb
class Employee2 < ApplicationRecord
	has_one :attendance2
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :uid, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 helper_method :current_user
  def current_user
	if session[:user_id]
  	@current_user ||= User.find(session[:user_id])
	else
	@current_user = nil
	end
  end
end

app/controllers/attendace3s_controller.rb
class Attendace3sController < ApplicationController
  before_action :set_attendace3, only: %i[ show edit update destroy ]

  # GET /attendace3s or /attendace3s.json
  def index
    @attendace3s = Attendace3.all
  end

  # GET /attendace3s/1 or /attendace3s/1.json
  def show
  end

  # GET /attendace3s/new
  def new
    @attendace3 = Attendace3.new
  end

  # GET /attendace3s/1/edit
  def edit
  end

  # POST /attendace3s or /attendace3s.json
  def create
    @attendace3 = Attendace3.new(attendace3_params)

    respond_to do |format|
      if @attendace3.save
        format.html { redirect_to @attendace3, notice: "Attendace3 was successfully created." }
        format.json { render :show, status: :created, location: @attendace3 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendace3.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendace3s/1 or /attendace3s/1.json
  def update
    respond_to do |format|
      if @attendace3.update(attendace3_params)
        format.html { redirect_to @attendace3, notice: "Attendace3 was successfully updated." }
        format.json { render :show, status: :ok, location: @attendace3 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendace3.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendace3s/1 or /attendace3s/1.json
  def destroy
    @attendace3.destroy
    respond_to do |format|
      format.html { redirect_to attendace3s_url, notice: "Attendace3 was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendace3
      @attendace3 = Attendace3.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendace3_params
      params.require(:attendace3).permit(:employeeid, :employeename, :date, :intime, :outtime, :discription)
    end
end

app/controllers/employee2s_controller.rb
class Employee2sController < ApplicationController
  before_action :set_employee2, only: %i[ show edit update destroy ]

  # GET /employee2s or /employee2s.json
  def index
    @employee2s = Employee2.all
  end

  # GET /employee2s/1 or /employee2s/1.json
  def show
  end

def list
  @employee2=Employee2.all
  
end
  # GET /employee2s/new
  def new
    @employee2 = Employee2.new
  end

  # GET /employee2s/1/edit
  def edit
  end

  # POST /employee2s or /employee2s.json
  def create
    @employee2 = Employee2.new(employee2_params)

    respond_to do |format|
      if @employee2.save
        format.html { redirect_to @employee2, notice: "Employee2 was successfully created." }
        format.json { render :show, status: :created, location: @employee2 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee2s/1 or /employee2s/1.json
  def update
    respond_to do |format|
      if @employee2.update(employee2_params)
        format.html { redirect_to @employee2, notice: "Employee2 was successfully updated." }
        format.json { render :show, status: :ok, location: @employee2 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee2s/1 or /employee2s/1.json
  def destroy
    @employee2.destroy
    respond_to do |format|
      format.html { redirect_to employee2s_url, notice: "Employee2 was successfully destroyed." }
      format.json { head :no_content }
    end
  end
    


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee2
      @employee2 = Employee2.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee2_params
      params.require(:employee2).permit(:firstname, :lastname, :salary, :gender, :contact, :email, :country, :city, :pincode, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_uid(params[:uid])
  if user && user.authenticate(params[:password])
     session[:uid] = user.id
     redirect_to(action:'welcome')
     
   else
     flash.now[:alert] = "Email or password is invalid"
     render "new"
end
  end

  def destroy
  	session[:user_id] = nil
    #redirect_to(action:'welcome')
      redirect_to home_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :gender, :contact, :city, :address, :password, :password_confirmation, :uid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendace3s_helper.rb
module Attendace3sHelper
end

app/helpers/attendance2s_helper.rb
module Attendance2sHelper
end

app/helpers/employee2s_helper.rb
module Employee2sHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendace3s/_form.html.erb
<%= form_with(model: attendace3) do |form| %>
  <% if attendace3.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendace3.errors.count, "error") %> prohibited this attendace3 from being saved:</h2>

      <ul>
        <% attendace3.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employeeid %>
    <%= form.number_field :employeeid %>
  </div>

  <div class="field">
    <%= form.label :employeename %>
    <%= form.text_field :employeename %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :intime %>
    <%= form.text_field :intime %>
  </div>

  <div class="field">
    <%= form.label :outtime %>
    <%= form.text_field :outtime %>
  </div>

  <div class="field">
    <%= form.label :discription %>
    <%= form.text_field :discription %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendace3s/edit.html.erb
<h1>Edit Attendance</h1>

<%= render 'form', attendace3: @attendace3 %>




<%= link_to '<button type="button">Back</button>'.html_safe, attendace3s_path %>

app/views/attendace3s/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Attendance</h1>
<style>
    

    table,th,td
    {
      border:1px solid black;
      
    border-radius: 5px;
      padding: 10px;

    }
    th,td
    {
      padding: 10px;
  background-color: hsl(316, 14%, 78%);
  color: black
}

  
    }

  </style>


<table>
  <thead>
    <tr>
      <th>Employeeid</th>
      <th>Employeename</th>
      <th>Date</th>
      <th>Intime</th>
      <th>Outtime</th>
      <th>Discription</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @attendace3s.each do |attendace3| %>
      <tr>
        <td><%= attendace3.employeeid %></td>
        <td><%= attendace3.employeename %></td>
        <td><%= attendace3.date %></td>
        <td><%= attendace3.intime %></td>
        <td><%= attendace3.outtime %></td>
        <td><%= attendace3.discription %></td>
        <td><%= link_to 'Show', attendace3 %></td>
        <td><%= link_to 'Edit', edit_attendace3_path(attendace3) %></td>
        <td><%= link_to 'Destroy', attendace3, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to '<button type="button">New Attendance</button>'.html_safe, new_attendace3_path %>
<%= link_to '<button type="button">Back</button>'.html_safe, welcome_path %>

app/views/attendace3s/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendace3: @attendace3 %>

<%= link_to 'Back', attendace3s_path %>
<h2> <%= link_to 'Back To Homepage', home_index_path %> </h2>

app/views/attendace3s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employeeid:</strong>
  <%= @attendace3.employeeid %>
</p>

<p>
  <strong>Employeename:</strong>
  <%= @attendace3.employeename %>
</p>

<p>
  <strong>Date:</strong>
  <%= @attendace3.date %>
</p>

<p>
  <strong>Intime:</strong>
  <%= @attendace3.intime %>
</p>

<p>
  <strong>Outtime:</strong>
  <%= @attendace3.outtime %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @attendace3.discription %>
</p>

<%= link_to 'Edit', edit_attendace3_path(@attendace3) %> |
<%= link_to 'Back', attendace3s_path %>
<h2> <%= link_to 'Back', home_index_path %> </h2>

app/views/employee2s/_form.html.erb
<center>
<style>
  body{
    background-image: url(https://thumbor.forbes.com/thumbor/fit-in/1200x0/filters%3Aformat%28jpg%29/https%3A%2F%2Fblogs-images.forbes.com%2Fpavelkrapivin%2Ffiles%2F2018%2F09%2FHappy-Employee-Working-Laptop-AdobeStock_171333654-by-By-Drobot-Dean-1200x801.jpg);
    background-repeat: no-repeat;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
   background-size: 100% 100%;
   font-size: 20px;
   font-family: "Times New Roman", Times, serif;

  }
</style>
<%= form_with(model: employee2) do |form| %>
  <% if employee2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee2.errors.count, "error") %> prohibited this employee2 from being saved:</h2>

      <ul>
        <% employee2.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :pincode %>
    <%= form.number_field :pincode %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</center>

app/views/employee2s/edit.html.erb
<h1>Edit Employee</h1>

<%= render 'form', employee2: @employee2 %>

<%= link_to 'Show', @employee2 %> |
<%= link_to 'Back', employee2s_path %>

app/views/employee2s/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Employee</h1></center>
<style>
    

    table,th,td
    {
      border:1px solid black;
      
    border-radius: 5px;
      padding: 10px;

    }
    th,td
    {
      padding: 10px;
  background-color: hsl(316, 14%, 78%);
  color: black
}

  
    }

  </style>
<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Salary</th>
      <th>Gender</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Country</th>
      <th>City</th>
      <th>Pincode</th>
      <th>Address</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @employee2s.each do |employee2| %>
      <tr>
        <td><%= employee2.firstname %></td>
        <td><%= employee2.lastname %></td>
        <td><%= employee2.salary %></td>
        <td><%= employee2.gender %></td>
        <td><%= employee2.contact %></td>
        <td><%= employee2.email %></td>
        <td><%= employee2.country %></td>
        <td><%= employee2.city %></td>
        <td><%= employee2.pincode %></td>
        <td><%= employee2.address %></td>
        <td><%= link_to 'Show', employee2 %></td>
        <td><%= link_to 'Edit', edit_employee2_path(employee2) %></td>
        <td><%= link_to 'Destroy', employee2, method: :delete, data: {confirm: 'Are you sure?'} %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<center>
<%= link_to '<button type="button">New Employee</button>'.html_safe, new_employee2_path %>
<%= link_to '<button type="button">Back</button>'.html_safe, welcome_path %>

app/views/employee2s/new.html.erb
<center><h1>New Employee</h1>

<%= render 'form', employee2: @employee2 %>

<%= link_to '<button type="button">Back</button>'.html_safe, employee2s_path %>
<%= link_to '<button type="button">Back TO Homepage</button>'.html_safe, home_index_path%>

app/views/employee2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @employee2.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee2.lastname %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee2.salary %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @employee2.gender %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @employee2.contact %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee2.email %>
</p>

<p>
  <strong>Country:</strong>
  <%= @employee2.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee2.city %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @employee2.pincode %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee2.address %>
</p>

<%= link_to 'Edit', edit_employee2_path(@employee2) %> |
<%= link_to 'Back', employee2s_path %>

app/views/home/about.html.erb



<div class="about-section">
  <h1>About Us</h1>
 <strong ><blockquote>Some text about who we are and what we do.</p>
  <p>Resize the browser window to see that this page is responsive by the way.</p>
  An employee contributes labor and expertise to an endeavor of an employer or of a person conducting a business or undertaking (PCB)[2] and is usually hired to perform specific duties which are packaged into a job. In a corporate context, an employee is a person who is hired to provide services to a company on a regular basis in exchange for compensation and who does not provide these services as part of an independent business.[3]

An issue that arises in most companies, especially the ones that are in the gig economy, is the classification of workers. A lot of workers that fulfill gigs are often hired as independent contractors.  

As a general principle of employment law, in the United States, there is a difference between an agent and an independent contractor. The default status of a worker is employee unless specific guidelines are met, which can be determined by the ABC test.[4] Thus, clarifying whether someone who performs work is an independent contractor or an employee from the beginning, and treating them accordingly, can save a company from trouble later on.</blockquote>


</div>

<h2 style="text-align:left">Our Team</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="https://img.freepik.com/free-vector/meeting-business-people-avatar-character_24877-57276.jpg?size=626&ext=jpg" alt="Jane" style="width:20%">
     	 <img src="https://media.gettyimages.com/photos/group-portrait-from-a-corporate-office-in-india-picture-id1144645913?s=612x612" alt="Jane" style="width:20%">
      <div class="container">
        <h2>Jane Doe</h2>
        <p class="title">CEO & Founder</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
       
      </div>
    </div>
  </div>

<h2> <%= link_to 'Back', home_index_path %> </h2>
  

app/views/home/index.html.erb
<html>
<head>
	<center>
	
<style>

ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;

 
  background-image: url('https://images.app.goo.gl/46Zfqm5HeWPWkZ6t6.jpg');
}

li {
  float: left;
}

li a {
  display: block;
  padding: 8px;
}
</style>
</head>
</center>
</head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  margin: 0;
}

/* Style the header */
.header {
  background-color: #f1f1f1;
  padding: 2px;
  text-align: center;
  font-family: DejaVu Sans Mono, monospace
  
}

/* Style the top navigation bar */
.topnav {
  overflow: hidden;
  background-color: #333;
}

/* Style the topnav links */
.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
    font-family: "Times New Roman", Times, serif;
}

/* Change color on hover */
.topnav a:hover {
  background-color: #ddd;
  color: black;
    font-family: "Times New Roman", Times, serif;
}
</style>
</head>
<body>

<div class="header">
  <h1>Employee Attendance Management System</h1>
</div>

<div class="topnav">
  <h2 align="left"><%= link_to 'Home', root_path %>
    <h2 align="left"><%= link_to 'About Me', home_about_path %>
     
   
     
 
<% if current_user %>
 Logged in as <%= current_user.id %>.
 <%= link_to 'Log Out', logout_path %>
<% else %>
<h2 align="left"> <li><%= link_to 'Log In', login_path %></li>
<% end %>
<p id='notice'><%= notice %></p>
 
</div>

</body>
</html>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cat</title>
    
<% begin %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track' => 'reload', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
<% rescue %>
  <script>
    window.location.replace "#{user_session_url()}"
  </script>
<% end %>

  <body>
    <style>

body {
  background-image: url('https://www.jenningswire.com/wp-content/uploads/2013/06/happy-business-team.jpg');
  background-repeat: no-repeat;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
   background-size: 100% 100%;
}
</style>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :uid %>
    <%= form.number_field :uid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Gender</th>
      <th>Contact</th>
      <th>City</th>
      <th>Address</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.gender %></td>
        <td><%= user.contact %></td>
        <td><%= user.city %></td>
        <td><%= user.address %></td>
        <td><%= user.uid %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<center>

<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', home_index_path %>
</center>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @user.contact %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>